insert into teacher (Name, Vorname, Email, Type)

values
('Aulepp','Simon','simon.aulepp@schule.hessen.de','1'),
('Bachmann','Meike','meike.bachmann@schule.hessen.de','1'),
('Backhaus','Benjamin','benjamin.backhaus@schule.hessen.de','1'),
('Dettmer','Annika','annika.dettmer@schule.hessen.de','1'),
('Di Fuccia','Violetta','violetta.difuccia@schule.hessen.de','1'),
('Donskoi','Kathrin','kathrin.donskoi@schule.hessen.de','1'),
('Eckhardt','Guido','guido.eckhardt@schule.hessen.de','1'),
('Eichner','Maria','maria.eichner@schule.hessen.de','1'),
('Emde','Christian','christian.emde@schule.hessen.de','1'),
('Emde','Sonja','sonja.emde@schule.hessen.de','1'),
('Fooken','Dierk','dierk.fooken@schule.hessen.de','1'),
('Franz','Silke','silke.franz@schule.hessen.de','1'),
('Fuhr','Gunther','manfred.fuhr@schule.hessen.de','1'),
('Gerhards','Björn','bjoern.gerhards@schule.hessen.de','1'),
('Gerland','Simone','simone.gerland@schule.hessen.de','1'),
('Geßner','Jörg','joerg.gessner@schule.hessen.de','1'),
('Görth','Meike','meike.goerth@schule.hessen.de','1'),
('Groß','René','rene.gross@schule.hessen.de','1'),
('Grüninger','Ursula','ursula.grueninger@schule.hessen.de','1'),
('Haas','Domenica','domenica.haas@schule.hessen.de','1'),
('Haferburg','Sven','sven.haferburg@schule.hessen.de','1'),
('Haschen','Heike','heike.haschen@schule.hessen.de','1'),
('Hofmann','Thomas','thomas.hofmann2@schule.hessen.de','1'),
('Hülsmann','Andreas','andreas.huelsmann@schule.hessen.de','1'),
('Huscher','Christopher','christopher.huscher@schule.hessen.de','1'),
('Kallmeyer','Alexander','alexander.kallmeyer@schule.hessen.de','1'),
('Kastmann','Katharina','ira.kastmann@schule.hessen.de','1'),
('Kunsch','Christiane','christiane.kunsch@schule.hessen.de','1'),
('Likci','Lara','lara.likci@schule.hessen.de','1'),
('Lindner','Annika','annika.lindner@schule.hessen.de','1'),
('Lingelbach','Constanze','constanze.lingelbach@schule.hessen.de','1'),
('Meyfarth','Thorsten','thorsten.meyfarth@schule.hessen.de','1'),
('Müller','Nora','nora.mueller2@schule.hessen.de','1'),
('Neumann-Westhof','Britta','britta.neumann-westhof@schule.hessen.de','1'),
('Neuner','Jeanette','jeanette.neuner@schule.hessen.de','1'),
('Nitsch','Anne','anne-kristin.nitsch@schule.hessen.de','1'),
('Nordmeier','Beatrice','beatrice.nordmeier@schule.hessen.de','1'),
('Otto','Kerstin','kerstin.otto@schule.hessen.de','1'),
('Pfeifer','Max','max.pfeifer@schule.hessen.de','1'),
('Philipp','Jasmina','jasmina.philipp@schule.hessen.de','1'),
('Reiß-Jäger','Philipp','philipp.reiss-jaeger@schule.hessen.de','1'),
('Ritter','Alexandra','alexandra.ritter@schule.hessen.de','1'),
('Rosenkranz','Susanne','susanne.rosenkranz@schule.hessen.de','1'),
('Schmoll','Anna-Lena','anna-lena.schmoll@schule.hessen.de','1'),
('Schulze','Sabine','sabine.schulze2@schule.hessen.de','1'),
('Schulze','Stephanie','stephanie.schulze@schule.hessen.de','1'),
('Sivrić-Peša','Sanela','sanela.sivric-pesa@schule.hessen.de','1'),
('Sommerfeld','Lisa','lisa.sommerfeld@schule.hessen.de','1'),
('Söther','Kai','kai.soether@schule.hessen.de','1'),
('Trusheim','Bernd','bernd.trusheim@schule.hessen.de','1'),
('Ventura','Maria João','maria.venturacorceiromendes@schule.hessen.de','1'),
('Weyer','Annabelle','annabelle.weyer@schule.hessen.de','1'),
('Witte','Jan-Patrick','jan-patrick.witte@schule.hessen.de','1'),
('Wittwer','Thomas','thomas.wittwer@schule.hessen.de','1'),
('Brandstäter','Saskia','saskia.brandstäter@schule.hessen.de','1'),
('Fischer','Marie-Charlott','marie-charlott.fischer@schule-hessen.de','1'),
('Giller','Jana','jana.giller@schule.hessen.de','1'),
('Göbel','Tim','tim.goebel@schule.hessen.de','1'),
('Keßler','Jana','jana.kessler@schule.hessen.de','1'),
('Knauf','Theresa','theresa.knauf@schule.hessen.de','1'),
('Kumerics','Andreas','andreas.kumerics@schule.hessen.de','1'),
('Linß','Caroline','caroline.linss@schule.hessen.de','1'),
('Pavel','Katja','katja.pavel@schule.hessen.de','1'),
('Richter','Sascha','sascha.richter2@schule.hessen.de','1'),
('Tunalioglu','Damla','damla.tunalioglu@schule.hessen.de','1'),
('Rainer','Beckert','rainer.beckert@schule.hessen.de','1'),
('Bock','Norbert','norbert.bock@schule.hessen.de','1'),
('Brauer','Florian','flobrauer@web.de','1'),
('Detka','Lena','lena.detka@schule.hessen.de','1'),
('Hoeppe','Christine','christine.hoeppe@schule.hessen.de','1'),
('Lutz','Burkhard','b.lutz@osw-kassel.de','1'),
('Müller','Tanja','tanja.mueller@schule.hessen.de','1'),
('Noske','Silke','silke.noske@schule.hessen.de','1'),
('Pengel','Tobias','tobias.pengel@schule.hessen.de','1'),
('Perl','Annika','annika.perl@schule.hessen.de','1'),
('Starke','Petra','petra.starke@schule.hessen.de','1'),
('Zitouni','Khaira-Salima','khaira-salima.zitouni@schule.hessen.de','1'),
('Niklas','Brede','niklas.brede@schule.hessen.de','1'),
('Förster','Julia','julia.foerster2@schule.hessen.de','1'),
('Hilberg','Tatiana','tatiana.hilberg@schule.hessen.de','1'),
('Müller','Edmund','edekassel@t-online.de','1');


insert into Kurse (Name, Jahrgang, Stundenzahl, Fach, Type)

values
('Bigband01','Q2','2','MU','2'),
('Cafeteria01','Q2','2','D','2'),
('Chor01','Q2','2','MU','2'),
('Orchester01','Q2','2','MU','2'),
('Q2BIO03','Q2','5','BIO','1'),
('Q2BIO04','Q2','5','BIO','1'),
('Q2BIO08','Q2','3','BIO','0'),
('Q2CH bio 07','Q2','3','CH','0'),
('Q2CH01','Q2','3','CH','1'),
('Q2CH09','Q2','3','CH','0'),
('Q2D07','Q2','4','D','0'),
('Q2D08','Q2','4','D','0'),
('Q2D09','Q2','4','D','0'),
('Q2D11','Q2','4','D','0'),
('Q2D13','Q2','4','D','0'),
('Q2DSP07','Q2','3','DSP','0'),
('Q2DSP08','Q2','3','DSP','0'),
('Q2DSP10','Q2','3','DSP','0'),
('Q2E01','Q2','5','E','1'),
('Q2E02','Q2','5','E','1'),
('Q2E04','Q2','5','E','1'),
('Q2E05','Q2','5','E','1'),
('Q2E06','Q2','5','E','1'),
('Q2E07','Q2','3','E','0'),
('Q2E08','Q2','3','E','0'),
('Q2E10','Q2','3','E','0'),
('Q2ETHI07','Q2','3','ETHI','0'),
('Q2ETHI08','Q2','3','ETHI','0'),
('Q2ETHI11','Q2','3','ETHI','0'),
('Q2ETHI12','Q2','3','ETHI','0'),
('Q2ETHI13','Q2','3','ETHI','0'),
('Q2G bili10','Q2','3','G','0'),
('Q2G01','Q2','5','G','1'),
('Q2G07','Q2','3','G','0'),
('Q2G08','Q2','3','G','0'),
('Q2G09','Q2','3','G','0'),
('Q2G12','Q2','3','G','0'),
('Q2G15','Q2','3','G','0'),
('Q2KU07','Q2','3','KU','0'),
('Q2KU09','Q2','3','KU','0'),
('Q2KU10','Q2','3','KU','0'),
('Q2M01','Q2','5','M','1'),
('Q2M02','Q2','5','M','1'),
('Q2M10','Q2','4','M','0'),
('Q2M11','Q2','4','M','0'),
('Q2M12','Q2','4','M','0'),
('Q2M13','Q2','4','M','0'),
('Q2M14','Q2','4','M','0'),
('Q2MU01','Q2','5','MU','1'),
('Q2PH01','Q2','5','PH','1'),
('Q2PH07','Q2','3','PH','0'),
('Q2PH08','Q2','3','PH','0'),
('Q2PH09','Q2','3','PH','0'),
('Q2PH10','Q2','3','PH','0'),
('Q2PH11','Q2','3','PH','0'),
('Q2POWI02','Q2','5','POWI','1'),
('Q2POWI08','Q2','3','POWI','0'),
('Q2POWI09','Q2','3','POWI','0'),
('Q2POWI11','Q2','3','POWI','0'),
('Q2POWI12','Q2','3','POWI','0'),
('Q2REV07','Q2','3','REV','0'),
('Q2REV09','Q2','3','REV','0'),
('Q2SPO Abi15','Q2','3','SPO','0'),
('Q2SPO10','Q2','3','SPO','0'),
('Q2SPO11','Q2','3','SPO','0'),
('Q2SPO12','Q2','3','SPO','0'),
('Q2SPO13','Q2','3','SPO','0'),
('Q2SPO14','Q2','3','SPO','0'),
('Q2SPO16','Q2','3','SPO','0'),
('Q2TUT09','Q2','1','TUT','3'),
('Q2TUT10','Q2','1','TUT','3'),
('Q2TUT11','Q2','1','TUT','3'),
('Q2TUT12','Q2','1','TUT','3'),
('Q2TUT14','Q2','1','TUT','3'),
('Q2TUT15','Q2','1','TUT','3'),
('Q2TUT16','Q2','1','TUT','3'),
('Q2TUT17','Q2','1','TUT','3'),
('Q2WIWI01','Q2','5','WIWI','1'),
('Q2WIWI07','Q2','4','WIWI','0'),
('ÜGINFO07','Q2','3','INFO','0');

CREATE TABLE Kursteilnehmer (
    Kurs_ID int,
    Personen_ID int,
    FOREIGN KEY (PersonID) REFERENCES Persons(PersonID)
); 


